### ISSUE TITLE
crash plugins farms

### ISSUE THREAD

**Issue by ghost** [HmHmmHm/Farms#2]
when i run plugins in genisys , it have crash . can you fix it!

Error: Declaration of ifteam\Farms\CocoaBeanBlock::canBeActivated() must be compatible with pocketmine\block\Block::canBeActivated(): bool
File: /92-Farms_v0-e68b8/src/ifteam/Farms/Farms
Line: 0
Type: E_COMPILE_ERROR

**Comment by KennMinao** [comment]
Same error

**Comment by GlacierShard92** [comment]
same
